typography_spectrum: 0.50332
color:
  brandColors:
    - '#ffffff'
    - '#71706e'
    - '#d9d8d6'
    - '#b8b8b8'
    - '#e67817'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74177
analytics:
  google: null
  facebook: null
  twitter: null
name: ProjectK
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: How CEOs can make mental flexibility a valuable asset
    id: c9b46141-75ee-40f3-a50a-6f5c2930ad5b
    type: content
favicon: null
title: Kanvic
purpose: []
