name: ProjectK
favicon: null
layout_spectrum: 0.24585
typography_spectrum: 0.82889
title: Kanvic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffdfc'
    - '#e7792b'
    - '#0092b6'
    - '#c72a3f'
    - '#1d1c1c'
  brandStrength: 1
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
