name: ProjectK
favicon: null
layout_spectrum: 0.74447
typography_spectrum: 0.50332
title: Kanvic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#71706e'
    - '#d9d8d6'
    - '#b8b8b8'
    - '#e67817'
  brandStrength: 0.6875
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
