name: ProjectK
favicon: null
layout_spectrum: 0.88351
typography_spectrum: 0.7417
title: Kanvic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5
  lightness: 0.9060083590447903
  saturation: 0.4375
  rhythmicContrast: 0.9522393483202904
purpose: []
