typography_spectrum: 0.50332
color:
  brandColors:
    - '#ffffff'
    - '#71706e'
    - '#d9d8d6'
    - '#b8b8b8'
    - '#e67817'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74177
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cc4d7a1f-095b-49f1-9631-d4263e1fc786.jpg
name: ProjectK
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: How CEOs can make mental flexibility a valuable asset
    id: c9b46141-75ee-40f3-a50a-6f5c2930ad5b
    type: content
  - name: How strategic thinkers expand their options
    id: 66b49f60-a155-44d0-a469-eab742b2377f
    type: content
  - name: The power of peripheral vision in strategic thinking
    id: 9389f5c1-8944-479f-ae83-a5698f10fbc0
    type: content
  - name: The Elephant tracks the dragon
    id: d0a47497-7fdb-41d9-9778-6b83083eae50
    type: content
favicon: null
title: Kanvic
purpose: []
