name: ProjectK
favicon: null
layout_spectrum: 0.49004
typography_spectrum: 0.82889
title: Kanvic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#71706e'
    - '#d9d8d6'
    - '#b8b8b8'
    - '#e67817'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
